### PR TITLE
Adding bower.json file. Fixes #361.

### LINKED ISSUE #361: Add a bower.json file
Installing rickshaw with bower includes everything. It would be nice if you added a bower.json file to ignore all but the source files.

http://bower.io/

### PR DESCRIPTION
**Pull request by aendrew**
As per #361, this adds a basic bower.json file. 

Might I also suggest using Bower for dependency management in general? This would involve adding a .bowerrc file saying to use `vendor` instead of `bower_components`, and rewriting the examples to point to something like `/vendor/d3/d3.js` instead.

### CODE REVIEW

**Comment by tgolen** [comment]
Adding this lib to bower would be a huge benefit. I would love to see this PR accepted.

**Comment by MichielDeMey** [comment]
+1 for Bower dependencies.

**Comment by iloire** [comment]
+1

**Comment by miranl** [comment]
:+1:

**Comment by slopetown** [comment]
+1

**Comment by aendrew** [comment]
Bower is dead! Long live npm! :tada:

**Pull request closed without merging**
