### PR TITLE
Updating dependencies

### PR DESCRIPTION
**Pull request by cesine**
* updated the dependancies
* updated the node engine
* modified the travis config to run the build minification

Caveats:
* certain versions of `jsdom` works either with node < 0.12 or with node > 4 not both. This means you can still install and use the package at node 0.8, 0.10 and 0.12, but you wont be able to run the tests on an older engine unless you also install a previous version of jsdom.
* there was a change in the insignificant digits of the sample svgs... this might introduce a breaking change for some of the users tests?

@wilmoore  what do you think?

### CODE REVIEW

**Comment by wilmoore** [comment]
> but you wont be able to run the tests on an older engine unless you also install a previous version of jsdom.

@cesine I think this is a fair trade-off as long as we note it in the `readme.md` with these changes.

**Comment by wilmoore** [comment]
> there was a change in the insignificant digits of the sample svgs... this might introduce a breaking change for some of the users tests?

If this does indeed introduce a break, then we should release a new major version once we feel comfortable cutting a release.

**Comment by cesine** [comment]
@wilmoore i put it at `1.6.0-rc.0`which gives space for more merged prs. this one makes it easier to run the tests so i'm going to merge it in so it will be faster to add tests to some of the older prs

**Comment by wilmoore** [comment]
:+1

**Pull request merged**
