### PR TITLE
Range selection tool

### PR DESCRIPTION
**Pull request by Andertech**
I made this range selection tool, the example is on rangeSelector.html
It pretty much covers the mouse selection behavior and zooming yet it still could use some improvement.

### CODE REVIEW

**Comment by ngo** [comment]
@Andertech What is the recommended way to use your selection tool alongside with mainline code? Is it sufficient to just include Rickshaw.Graph.RangeSelector.js file from your repository?

**Comment by Andertech** [comment]
@ngo https://gist.github.com/Andertech/606f35c0d8feb64c869c should work

**Comment by Andertech** [comment]
btw I'm closing this, I might revisit or not.

**Comment by niemyjski** [comment]
It would be really nice if this was officially supported. I've made a bunch of fixes to it here: https://github.com/exceptionless/Exceptionless.UI/blob/master/src/components/rickshaw/rickshaw-custom.js

**Comment by Andertech** [comment]
I know, but we can also use it as a module, so it's no biggie.
I don't plan to keep track on this for the time being, but feel free to make a new PR if you feel like it.
Also @niemyjski feel free to check my previous answer to @ngo where i showed him a more developed code than what's on this PR.

**Pull request closed without merging**
